### ISSUE TITLE
babel-plugin-flow-runtime: log to console instead of throwing

### ISSUE THREAD

**Issue by panrafal** [codemix/flow-runtime#10]
We use a modified version of typecheck plugin which uses `console.error(message, value)` instead of throw. Firstly, it's less of a hindrance in development; secondly, it allows to inspect the actual value, not only it's type signature.

Would you consider adding an option to babel plugin, or point me in a direction where it should be implemented?

**Comment by phpnode** [comment]
I really want this too, I was thinking about this last night, right now every type has an `.assert()` method which either returns its input if it is valid or throws, and `.accepts()` which returns a boolean. I'm not sure if I really want to expand on this - it seems like having `t.string().warn(123)` is cluttering up the API.
Maybe the best place for this to go would be on `TypeContext`:

```js
const stringOrNum = t.union(t.string(), t.number());

t.warn(stringOrNum, "ok"); // "ok"
t.warn(stringOrNum, 123); //  123
t.warn(stringOrNum, [true, false]); // logs an error but still returns [true, false].
```

Then we can have an option like `warn: true` in `.babelrc`
