### ISSUE TITLE
Opportunity to use in production on NodeJS

### ISSUE THREAD

**Issue by MrEfrem** [codemix/flow-runtime#101]
This is a:

 - [ ] Bug Report
 - [ ] Feature Request
 - [x] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

You write in README.md (`babel-plugin-flow-runtime`):
```
Which is very safe, and can be very useful during development, but has a non-trivial performance overhead. It's usually a good idea to disable this feature in production.
```

But I use it in production for microservices on `NodeJS`.  It is good idea?

**Comment by ForbesLindesay** [comment]
It will cause a significant performance overhead, so it's not a very good idea.  However, if you are not worried about performance, it shouldn't really cause any significant problems.
