### ISSUE TITLE
Check code during compile?

### ISSUE THREAD

**Issue by terion-name** [codemix/flow-runtime#102]
This is a:

 - [x] Question

Which concerns:

 - [x] babel-plugin-flow-runtime

Is there a way to make this plugin check code in compile time and throw exception? Something like this:
<img width="1081" alt="2017-04-29 00 05 46" src="https://cloud.githubusercontent.com/assets/1060205/25547407/a8440016-2c6f-11e7-98d2-480105f501d2.png">

**Comment by phpnode** [comment]
No, we don't want to replicate Flow itself, so we don't really do any static analysis.
