### ISSUE TITLE
Will this support refinement likes tcomb or flowio?

### ISSUE THREAD

**Issue by linonetwo** [codemix/flow-runtime#11]
As homepage said:  

> It builds on our previous work with babel-plugin-typecheck, but shares a lot of ideas with the work of Giulio Canti and others on tcomb and flow-io.

Will flow-runtime supports refinement?

**Comment by phpnode** [comment]
Yes, we already support type refinements via `addConstraint()` but would like to make this nicer - https://github.com/codemix/flow-runtime/issues/6

**Comment by phpnode** [comment]
Here's some docs: https://codemix.github.io/flow-runtime/#/docs/type-refinements
