### ISSUE TITLE
Nullable and optional properties

### ISSUE THREAD

**Issue by fabiandev** [codemix/flow-runtime#119]
This is a:

 - [ ] Bug Report
 - [ ] Feature Request
 - [x] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

Making a property of a type nullable behaves the same as if it was optional.

```js
const A = t.type("A", t.object(t.property("a", t.nullable(t.boolean()))));
const B = t.type("B", t.object(t.property("a", t.boolean(), true)));

A.assert({}); // passes
B.assert({}); // passes
```
---

### What is the expected behaviour?

I was expecting that a nullable property has to be set, but accepts null values, and optional properties may be omitted.

```js
A.assert({a: null}); // passes
A.assert({a: undefined}; // passes
A.assert({}); // fails (property "a" does not exist)
```
---

### Which package versions are you using?

I used the live demo: https://codemix.github.io/flow-runtime

**Comment by phpnode** [comment]
In Flow `nullable` means `null | void`, so we simply check for `value == null`, we don't check that the property itself exists. Would accept a PR to change this

**Comment by fabiandev** [comment]
I would definitely look into this. Could you give me a hint on where to start? `ObjectType`, `ObjectTypeProperty` or the `NullableType` itself?

As I'd need to add some checks if the input of an object type has the property set if it is nullable (static or non-static), I should probably start by looking at the `accepts` of `ObjectType`?

Do you think it is better to introduce a new type alongside `NullableType` to not introduce breaking changes?

**Comment by phpnode** [comment]
`ObjectTypeProperty` is the right place I think, we shouldn't introduce a new type for it - like flow, every release of flow-runtime breaks compatibility in some way because it typically gets stricter  / more comprehensive

**Comment by samhagan** [comment]
This change seems inconsistent with Flow, which allows { field: ?number } to be null, undefined/void, or a number, which means that it can also be omitted.  This is preventing us from upgrading from 0.12.0 without some material type changes.  Could we make this configurable via options?  Happy to look at doing a PR.

**Comment by fabiandev** [comment]
@samhagan I think the current behavior is fine. While Flow allows the property to be `null` or `undefined`, it must exist on the object (see [example](https://flow.org/try/#0C4TwDgpgBAglC8UDeAoKUwCcD2YBcUA-AHYCuAtgEYSYDcKAvvSqJFAEILJoY5iEEyVGvSYpxAeglQAzqQDG8iDJmDSAG3UBDSuuhZcNUFABuW9aWjUAlsQDmUUsQAmEAGa2IziWU3i9wFBaAIwEcIio6Ab4ji7uns6MzAFBAExhXJG8uGp+YpLScorKqlC4wNbYxObZkJjGxNiBrh7EXv4QgZShHJn5KFJQNDiYudq6+nxGIFCNzfFtiSgpWgDMGRFiQA)).

**Comment by samhagan** [comment]
@fabiandev thanks for the quick reply.  I hadn't noticed that...this is happening to us on api boundaries, so the strictness just highlighted bad type definitions.

**Comment by christophehurpeau** [comment]
How would you type a options object then ?

```js
type OptionsType = {|
  a: ?number,
  b: ?string,
|};

const fn = (options: OptionsType = {});

fn(); // should not throw
fn({}); // should not throw
fn({ a: 10 }); // should not throw
```

**Comment by fabiandev** [comment]
@christophehurpeau Actually what you described is not the current behavior of exact objects in flow (see [example](https://flow.org/try/#0C4TwDgpgBAggjFAvFA3gHymATgezALigDsBXAWwCMIso0BfAbgCgAbCYKAQzkPiVUZQA9EKjVcWJk1CRYAJn7pMuMAH5CpStVqNW7LnN4LkKQSLFYJUmdBgBmRRmx5CqzVRr1mbDpzu8HEzNRcRxJIA) and this related [issue](https://github.com/facebook/flow/issues/2386)).

```js
type A1 = {| prop: number |};
let a1: A1 = {}; // error

type A2 = {| prop?: number |};
let a2: A2 = {}; // error

type A3 = {| prop: ?number |};
let a3: A3 = {}; // error
```

Anyway, it seems that `flow-runtime` does not align with the behavior of exact objects in flow.

**Comment by christophehurpeau** [comment]
@fabiandev thanks for your answer 👍 

so the answer is:

```js
type OptionsType = {
  a?: number,
  b?: string,
};

const fn = (options: OptionsType = {}) => options;

fn(); // do not throw
fn({}); // do not throw
fn({ a: 10 }); // do not throw
```

[flow try example](https://flow.org/try/#0C4TwDgpgBA8mwEsD2A7AzgFXNAvFA3gFBRQCGA-AFxQoCuAtgEYQBOANMVI1VGsCwhQBzDgF8A3IUIBjVHygAzFFDwAKJPGTpqcRHKyQVBUQEoVAPiga96SYSWqT4qAHoXvABZJaAGwAmNEjAUMAeLEgA7vYoqvimzm6e3v6BwaHhUQ74ZNQAjAAMUPGu7mhevgEoQSFhkUA)

too bad the exact objects doesn't work 😞

**Comment by christophehurpeau** [comment]
There is a [workaround in the documentation]():

[Example](https://flow.org/try/#0C4TwDgpgBAogHgQwMbADwBUB8UC8V1QBkUAJAMoAWCkGmA3AFAOiRQDyYwAlgPYB2AZ3ThoeeMjQBvBlCgIA-AC4ofAK4BbAEYQATgBoZUTUqgDgOrnwDmBgL70mSfmagAzPrigAKHp16DlDm5nYVY8SVsASlxsX2DBRgZ3L0i6KAB6dNMKHlUAGwATFR5gKGAKHR4AdyS+LwjUjKyBHPyivhKyiura+rllAEYABigotMzs3MLi0vLKmt7JfqgAcgQV0caJlqmiuZ7kpaRBkbGmybau+YYgA)

```js
type Exact<T> = T & $Shape<T>;

type OptionsType = Exact<{
  a?: number,
  b?: string,
}>;

const fn = (options: OptionsType = {}) => options;

fn(); // should not throw
fn({}); // should not throw
fn({ a: 10 }); // should not throw

fn({ a: 'a' }); // should throw
fn({ c: 10 }); // should throw
```

flow-runtime throws the first one (`options.a must be a number`) but not the second one. Should I open another issue ?

**Comment by fabiandev** [comment]
Thanks for posting the workaround and for flagging the issue with flow-runtime. Opening another issue is probably a good idea to keep track of it.
