### ISSUE TITLE
Babel plugin is dropping keys from object types.

### ISSUE THREAD

**Issue by jcready** [codemix/flow-runtime#135]
This is a:

 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

I have a type which looks like this:

```js
type ODataAST = {|
  '$path'?: $path,
  '$select'?: $select,
  '$expand'?: $expand,
  '$filter'?: $filter,
  '$orderby'?: $orderby,
  '$callback'?: string,
  '$format'?: string,
  '$search'?: string,
  '$count'?: boolean,
  '$skip'?: number,
  '$top'?: number
|}
```

When I add flow-runtime validations using the babel plugin I end up with a bunch of RuntimeTypeErrors that look like this:

```
RuntimeTypeError: Return Type must be one of: {|
  $path?: $path | $select | $expand | $filter | $orderby | string | string | string | boolean | number | number;
|}

Expected: {|
  $path?: $path | $select | $expand | $filter | $orderby | string | string | string | boolean | number | number;
|}

Actual: {
  $select: Array<string>;
}
```

Notice that the the error message claims that the type only has a single key `$path` and all of the other keys that should be there have instead had their types joined together in a union and put onto `$path`.

---

### What is the expected behaviour?
I would expect babel-plugin-flow-runtime to correctly interpret the following type:

```js
type ODataAST = {|
  '$path'?: $path,
  '$select'?: $select,
  '$expand'?: $expand,
  '$filter'?: $filter,
  '$orderby'?: $orderby,
  '$callback'?: string,
  '$format'?: string,
  '$search'?: string,
  '$count'?: boolean,
  '$skip'?: number,
  '$top'?: number
|}
```

---

### Which package versions are you using?

```json
{
  "babel-core": "^6.25.0",
  "babel-plugin-flow-runtime": "^0.11.1",
  "babel-plugin-syntax-flow": "^6.18.0",
  "babel-preset-env": "^1.6.0",
  "flow-bin": "^0.50.0"
}
```

**Comment by jcready** [comment]
It turns out that if I remove the quotes around the keys of the object type then everything works. So it still seems like a bug, but it has a proper workaround at least.

```js
type ODataAST = {|
  $path?: $path,
  $select?: $select,
  $expand?: $expand,
  $filter?: $filter,
  $orderby?: $orderby,
  $callback?: string,
  $format?: string,
  $search?: string,
  $count?: boolean,
  $skip?: number,
  $top?: number
|}
```

That type works and produces the correct flow-runtime validations.

**Comment by phpnode** [comment]
This ended up being a bug with Babylon. Fixed in next release.
