### ISSUE TITLE
Instance Map class

### ISSUE THREAD

**Issue by lyxsus** [codemix/flow-runtime#139]
I can't understand why I can't instantiate class Map.

This is a:

 - [ ] Bug Report
 - [ ] Feature Request
 - [x] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?
`const foo: Map = new Map;`
as expected raises
`InvariantViolation: Must specify two type parameters for Map.`

but this one
`const foo: Map <string, string> = new Map;`
also raises an error
`RuntimeTypeError: Value must be an instance of Map`

---

### What is the expected behaviour?
No error in one of examples above.

---

### Which package versions are you using?
0.14.0

**Comment by antitoxic** [comment]
Same error here. Latest version of `flow-runtime` and  `babel-plugin-flow-runtime`.

**Comment by antitoxic** [comment]
I'm sorry to contribute to the infinite notifications that open source project like this has but I am tagging @phpnode (_as someone I see as recently active committer_) because this is very fundamental problem.

If there's not enough traction in flow-runtime, it would be nice to know so that the project that I use it with doesn't suffer.

**Comment by lyxsus** [comment]
In my case it was solved by disabling polyfills in babelrc:
`
		["transform-runtime", {
			"polyfill": false
		}],
`

That means, that flow-runtime correctly raises an error on different Map class implementations.

There should be some way to link flow-runtime Map class with polyfilled class, but I found no way to do it. In #82 @phpnode mentioned "libName" config option for "babel-plugin-flow-runtime" plugin, but haven't found it in docs or source code.

**Comment by phpnode** [comment]
Sorry for the delay, as you say this happens because the `Map` that you're using is polyfilled and `flow-runtime` is looking for the real, non-polyfilled `Map`. The same problem happens when using e.g. Mobx. the answer is to override the predicate on the type context, like this:

```js
import t from 'flow-runtime';
t.setPredicate('Map', input => input instanceof YourPolyfilledMap || input instanceof Map)
```
