### ISSUE TITLE
"type referenced from value position" error when using  t.param(...)

### ISSUE THREAD

**Issue by alekbarszczewski** [codemix/flow-runtime#148]
This is a:
 - [x] Question

Which concerns:
 - [x] flow-runtime
---

### What is the current behaviour?

```js
// @flow
import t from 'flow-runtime'

type MyParam = string

function myFunction (myParam: MyParam): void {
  t.param('myParam', MyParam).assert(myParam)
}
```

```
$ yarn flow
```

```sh
Error: src/test.js:8
  8:   t.param('myParam', MyParam).assert(myParam)
                          ^^^^^^^ MyParam. type referenced from value position
  5: type MyParam = string
          ^^^^^^^ type MyParam


Found 1 error
error Command failed with exit code 2.
```

---

### What is the expected behaviour?

Flow should not throw error, otherwise I can't use flow-runtime in my lib. Not sure if this is issue with Flow itself, or maybe flow need some extra options to make it work? Tried to find something about this error but it seems that others encountered it in other context (during importing/exporting types).

---

### Which package versions are you using?

"flow-runtime": "0.14.0"
"flow-bin": "0.54.1"
"babel-plugin-flow-runtime": "0.11.1"
"node": "v8.4.0"

**Comment by mAAdhaTTah** [comment]
This is not a bug. You need to `reify` the type first. See [here](https://codemix.github.io/flow-runtime/#/docs/working-with-flow).

**Comment by alekbarszczewski** [comment]
Thank you, this solves my issue!
