### ISSUE TITLE
Not compatible with latest Flow (React)

### ISSUE THREAD

**Issue by samhagan** [codemix/flow-runtime#149]
This is a:

 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

Flow >=0.53.0 modified how React classes are defined.  Instead of 3x type arguments (DefaultProps, Props, State), there are only 2x type arguments (Props, State). 

As-is, flow-runtime incorrectly maps `Props => DefaultProps` and `State => Props`, resulting in incorrect warnings/errors.

https://flow.org/en/docs/react/components/
https://medium.com/flow-type/even-better-support-for-react-in-flow-25b0a3485627

**Comment by johnryan** [comment]
@samhagan any update on this / anything I can take on to help move this forward?

**Comment by mikkom** [comment]
I would also love see the latest Flow versions supported. We're holding off on upgrading Flow because we wouldn't want to give up on flow-runtime 🙂 

What would it take to add the support? Maybe @phpnode would have some insight on this? I'm also happy to help wherever I can.

**Comment by amilajack** [comment]
Testing a fix for this here: https://github.com/amilajack/babel-plugin-flow-runtime
Installation:
```bash
npm install --save-dev github:amilajack/babel-plugin-flow-runtime
```

**Comment by mikkom** [comment]
@amilajack Nice work, thanks for the tip! I'll definitely try it out soon 👍
