### ISSUE TITLE
flow-runtime inaccurately reporting errors on intersection types

### ISSUE THREAD

**Issue by johnryan** [codemix/flow-runtime#156]
This is a:

 - [X] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [X] flow-runtime
 - [X] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?
If i have an intersection type `Baz`
```
type Foo = {
 val1: string 
}

type Bar = {
 val2: string
}

type Baz = Foo & Bar;
```

when i have a simple react class

```
type Props = {
  myBaz: Baz
}

componentWillReceiveProps(nextProps: Props) {
  console.log(props)
}
```
I get an error like this: 
```
 nextProps.myBaz.val2 must be a string
 Expected: string
 Actual: void
```

even though the value is there.

---

### What is the expected behaviour?
I would expect this to NOT be an error reported by flow-runtime

---

### Which package versions are you using?
"babel-plugin-flow-runtime": "0.11.1",
"flow-runtime": "0.14.0"

**Comment by phpnode** [comment]
hey, sorry for the delay, unfortunately [I couldn't replicate](https://github.com/codemix/flow-runtime/commit/e0b5b652f038c870bd510d0a480634d150b86cbe) this bug based on the example[here. If it's still an issue please post some example code which fails on the [Try Page](https://codemix.github.io/flow-runtime/#/try), and i'll reopen
