### ISSUE TITLE
Nullable property asserted when null

### ISSUE THREAD

**Issue by arabold** [codemix/flow-runtime#158]
This is a:

 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

I'm programmatically validating a value against a type definition like this:
```js
type MySchema = {
  foo: ?string;
}

const schemaType = (reify: Type< MySchema >);
const property = schemaType.getProperty("foo");
property.unwrap().assert("hello world"); // < works as expected
property.unwrap().assert(null); // < throws a RuntimeTypeError: Value must be a string
property.assert(null); // < throws a TypeError: Cannot read property 'optionalNilable' of null
```

---

### What is the expected behaviour?
It should be possible to pass in a `null` or `undefined` value and pass the assertions above, shouldn't it? Currently I have a workaround in place by first checking the `property.optional` flag before asserting.

---

### Which package versions are you using?
```
├── babel-plugin-flow-runtime@0.11.1
├── babel-preset-flow@6.23.0
├── eslint-plugin-flow-check@1.1.1
├── eslint-plugin-flowtype@2.39.1
├── flow-bamboo-reporter@0.3.0
├── flow-bin@0.54.1
├── flow-runtime@0.14.0
├── flow-runtime-validators@0.14.0
├── flow-typed@2.2.0
```

**Comment by phpnode** [comment]
I think the problem is that `unwrap()` unwraps too much, and is unwrapping the inner Nullable type.
