### ISSUE TITLE
Class Properties causes syntax error

### ISSUE THREAD

**Issue by ozum** [codemix/flow-runtime#176]
This is a:

 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [ ] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?
When I define a class property and its type, I got errors in transpiled files as below:

* `Unexpected token =` error using `transform-decorators-legacy`.
* `Unexpected character '@'` without using `transform-decorators-legacy`.

Is there a way to use class properties?

```js
class Test {
  a: number;

  constructor() {
    this.a = 2;
  }
}
``` 

```json
"plugins": [
    "add-module-exports",
    "transform-export-extensions",
    "transform-decorators-legacy", [
      "flow-runtime", {
        "assert": true,
        "annotate": true
      }
    ]
  ],
```
---

---

### Which package versions are you using?
babel-plugin-flow-runtime 0.15.0

**Comment by phpnode** [comment]
you need to enable the class properties transform (stage-2 i believe) and unfortunately we have a dependency on decorators when annotating classes. You should be able to avoid it if you turn `annotate` off, but then flow-runtime will be less accurate.
