### ISSUE TITLE
Feature Request: make some typings assertions, others annotations

### ISSUE THREAD

**Issue by andykais** [codemix/flow-runtime#208]
This is a:

 - [ ] Bug Report
 - [X] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [ ] flow-runtime
 - [X] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

All flow types become runtime assertions, which can have serious performance overheads. This means in a project that is used as a library, developers are encouraged to use flow types only for non performance heavy parts of a codebase. E.g. I have a library that users drop a config into to run some tasks. Using flow runtime, I will type the surface level api functions and leave everything else untyped.

---

### What is the expected behaviour?

If instead, there was a way to opt in for runtime behavior on certain flow typings, and ignore the rest, then a whole codebase could be properly typed without worrying about the performance overhead.

**Comment by jedwards1211** [comment]
@andykais you can use `["flow-runtime", {"assert": false, "optInOnly": true}]` in your babel configuration, and then in files you want to use flow-runtime, add `/* @flow-runtime enable */` at the top.  For my APIs I explicitly request assertions like this:

```js
// @flow
/* @flow-runtime enable */

import {reify} from 'flow-runtime'
import type {Type} from 'flow-runtime'

export type UpdateUserOptions = {
  +actorId: number,
  +userId: number,
  +values: $Shape<UserAttributes>,
}
export const UpdateUserOptionsType = (reify: Type<UpdateUserOptions>)

export async function assertCanUpdateUser(options: UpdateUserOptions): Promise<void> {
  assert(UpdateUserOptionsType, options)
  ...
}
```

**Comment by andykais** [comment]
oh awesome! Thank you I didnt not see that feature documented anywhere. This is a clean and simple way to do what I wanted

**Comment by jedwards1211** [comment]
btw this and other options for the babel plugin are documented [here](https://codemix.github.io/flow-runtime/#/babel-plugin-flow-runtime)
