### ISSUE TITLE
Can I choose where to do runtime checks?

### ISSUE THREAD

**Issue by harrykao** [codemix/flow-runtime#215]
This is a:

 - [ ] Bug Report
 - [ ] Feature Request
 - [x] Question
 - [ ] Other

Which concerns:

 - [ ] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

(Apologies if this is already documented. Please send me a link if it is.)

Is it possible to do runtime checks only in certain places? I'd like to check that server responses match what the client code is expecting but I don't want runtime checks anywhere else.

**Comment by jedwards1211** [comment]
Yes, use the `optInOnly` option for [`babel-plugin-flow-runtime`](https://codemix.github.io/flow-runtime/#/babel-plugin-flow-runtime).  Then annotate a file with `// @flow-runtime enable`.  This makes it convert types to runtime types in that file, but doesn't turn on assertions or function/class type annotations.
Reify a type you want to use:

```js
// @flow
// @flow-runtime enable

import {reify} from 'flow-runtime'
import type {Type} from 'flow-runtime'

type Foo = {
  foo: string,
}

export const FooType = (reify: Type<Foo>)
```

Then you can import this type anywhere and explicitly assert with it:

```js
// @flow

import {FooType, type Foo} from './Foo'

function fn(foo: Foo) {
  FooType.assert(foo)
}
```
