### ISSUE TITLE
Implement class property decorators

### ISSUE THREAD

**Issue by phpnode** [codemix/flow-runtime#22]
At the moment `babel-plugin-flow-runtime` generates decorators for typed class properties, but `t.decorate()` is not actually implemented yet. Need to implement it in a way that does not confound e.g. mobx

**Comment by gajus** [comment]
My issue seems to be related to this.

I have started getting an error:

```
/Users/gajus/Documents/dev/gajus/surgeon/src/sentinels/InvalidValueSentinel.js:13
@_flowRuntime2.default.annotate(_flowRuntime2.default.class('InvalidValueSentinel', _flowRuntime2.default.property('message', _flowRuntime2.default.string()), _flowRuntime2.default.method('constructor', _flowRuntime2.default.param('message', _flowRuntime2.default.string()))))
^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at loader (/Users/gajus/Documents/dev/gajus/surgeon/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/gajus/Documents/dev/gajus/surgeon/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/Users/gajus/Documents/dev/gajus/surgeon/node_modules/babel-cli/lib/_babel-node.js:154:22)
```

When using any annotations in the following class:

```js
// @flow

export default class InvalidValueSentinel {
  constructor (message = 'Unexpected value.') {
    this.message = message;
  }
}

```

The issue can be replicated by:

```bash
git clone https://github.com/gajus/surgeon
cd surgeon
npm install
NODE_ENV=development babel-node src/sentinels/InvalidValueSentinel.js
```

**Comment by phpnode** [comment]
@gajus looks like you need to add `babel-plugin-transform-decorators-legacy` to your list of plugins.

We currently have to use decorator syntax for this transform just in case the user themselves is using decorators, it would be nicer if we detected their presence and fell back to something that didn't depend on them.

**Comment by gajus** [comment]
Thank you

**Comment by gajus** [comment]
This issue keeps coming back to bite me.

The error itself is very frustrating since "Invalid or unexpected token" doesn't say much about the underlying issue. Luckily, there is Google that takes to this issue thread.

**Comment by phpnode** [comment]
@gajus agree, I would like to deal with this but I'm lacking time at the moment

**Comment by gajus** [comment]
No worries, I know the feeling.
