### ISSUE TITLE
Produce a separate browser build

### ISSUE THREAD

**Issue by ForbesLindesay** [codemix/flow-runtime#29]
In `TypeContext`, there are still generators.

**Comment by phpnode** [comment]
I think we need a separate browser build which uses regenerator. I had a play around with rollup a few days ago, I'll try and get it going some time this week, unless you'd like to make a PR? :)

**Comment by doctyper** [comment]
Pretty sure this would also fix #26.

**Comment by phpnode** [comment]
Added rollup and browser / commonjs / es2015 builds in v0.2.0

**Comment by ForbesLindesay** [comment]
Thanks!
