### ISSUE TITLE
Crashes when React Props type is an intersection

### ISSUE THREAD

**Issue by Dema** [codemix/flow-runtime#38]
This is a:

 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validatosr
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

Crashes in browser with

```
flow-runtime.js:5542Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at makeReactPropTypes (flow-runtime.js:5542)
    at TypeContext.propTypes (flow-runtime.js:7214)
    at Object.<anonymous> (App.js:14)
```
if I have Props for class defined as an intersection like this
```
type Props = {
  a?: number
} & {
  b?: string
}
class Z extends React.Component {
  props: Props
  render(){
    return <div/>
  }
}
```
Here is the create-react-app project that shows an error. Please, remove node_modules/flow-runtime/dist/*.min.js to make it work. Or else it'll crash with regeneratorRuntime is undefined.

[issue-flow-runtime-intersection.zip](https://github.com/codemix/flow-runtime/files/738339/issue-flow-runtime-intersection.zip)
---

### Which package versions are you using?

"flow-runtime": "0.2.1"

**Comment by phpnode** [comment]
Will try and get to this later today. We should make `IntersectionType.prototype.unwrap()` return an `ObjectType`

**Comment by eric-burel** [comment]
Hi, I can reproduce in v0.8.0, is this solved ?
