### ISSUE TITLE
no compile time errors

### ISSUE THREAD

**Issue by Radivarig** [codemix/flow-runtime#4]
I know it's called flow "runtime" but typecheck has compiletime type checking as well, for example `const a: string = 4`. Is this planned to be added?

**Comment by phpnode** [comment]
It's possible to do in very simple cases like the one you specified, but very hard to do it properly without reimplementing all of what Flow does. For some context, `babel-plugin-typecheck` was started when flow was very young and didn't support much ES6 so at the time it seemed like a good idea. As flow matured and got better (but more complicated), I ran into a lot of scenarios where code that passes with flow would fail with typecheck. The difference with this project is that it's designed to used together with Flow from the start, so it doesn't need to do the things that Flow does itself.

**Comment by phpnode** [comment]
Note: It's not that I'm against the idea - if Flow starts exposing type information in a more accessible way I'd love to integrate it to avoid extraneous checks, until then it's just too much work.
