### ISSUE TITLE
Document dependencies on other babel plugins

### ISSUE THREAD

**Issue by nunofgs** [codemix/flow-runtime#42]
This is a:

 - [x] Question

Which concerns:

 - [x] flow-runtime
 - [x] babel-plugin-flow-runtime

---

### What is the current behaviour?
I wanted to give this package a shot so I ran:

```bash
$ yarn init -y
$ yarn add flow-runtime
$ yarn add --dev babel-cli babel-plugin-flow-runtime
$ echo '{ "plugins": [["flow-runtime", { "assert": true, "annotate": true }]] }' > .babelrc
$ vim index.js
<paste example from https://codemix.github.io/flow-runtime/#/babel-plugin-flow-runtime>
$ babel index.js

SyntaxError: index.js: Unexpected token, expected ; (1:5)
> 1 | type User = {
    |      ^
  2 |     id: number;
  3 |       name: string;
  4 | };
```

---

### What is the expected behaviour?
I must be doing something wrong, obviously, but since I'm having these difficulties it might indicate that the "getting started" section needs some improvement.

---

### Which package versions are you using?
* "babel-cli": "6.22.2",
* "babel-plugin-flow-runtime": "0.2.1"
* "flow-runtime": "0.2.1"

**Comment by phpnode** [comment]
You're right, there is an implicit dependency on:

- decorator syntax
- class property syntax
- flow syntax

So really the `.babelrc` should look like:

```json
{
  "presets": [
    "stage-0",
    "react"
  ],
  "plugins": [
    "transform-decorators-legacy",
    ["flow-runtime", {"assert": true, "annotate": true}]
  ]
}
```

**Comment by phpnode** [comment]
Side note that I should add to the docs:

It's a bit unfortunate to depend on the `decorators` transform, especially as they're not totally specced yet, the problem is that people _do_ use decorators already, so if we want to interop nicely with them we must use them too. This could potentially be optional in future, we could only use them ourselves when other decorators are present.

**Comment by nunofgs** [comment]
Ah, it does indeed work! Thought I was going crazy over here 😄

**Comment by FredyC** [comment]
I got rather baffled about this too. Seeing in the documentation that I should install decorators plugin I was like "Why would I do that?". It's really super confusing why it's needed there... 

Perhaps it might be actually good idea to publish a whole babel preset that includes these dependencies and mention that in docs instead. Or those could be actual peer dependencies so we get warning about them missing.
