### ISSUE TITLE
Annotated function arguments and return value always default to ExistentialType

### ISSUE THREAD

**Issue by nunofgs** [codemix/flow-runtime#43]
This is a:

 - [x] Bug Report

Which concerns:

 - [x] flow-runtime

---

### What is the current behaviour?
```js
function foo(one: String, two: String): Number {
}

console.log(require('util').inspect(flow.typeOf(foo), { depth: null }));
```

Prints:

```js
FunctionType {
  typeName: 'FunctionType',
  context: TypeContext { mode: 'assert' },
  params:
   [ FunctionTypeParam {
       typeName: 'FunctionTypeParam',
       context: TypeContext { mode: 'assert' },
       name: 'a',
       type:
        ExistentialType {
          typeName: 'ExistentialType',
          context: TypeContext { mode: 'assert' } },
       optional: false },
     FunctionTypeParam {
       typeName: 'FunctionTypeParam',
       context: TypeContext { mode: 'assert' },
       name: 'b',
       type:
        ExistentialType {
          typeName: 'ExistentialType',
          context: TypeContext { mode: 'assert' } },
       optional: false } ],
  returnType:
   FunctionTypeReturn {
     typeName: 'FunctionTypeReturn',
     context: TypeContext { mode: 'assert' },
     type:
      ExistentialType {
        typeName: 'ExistentialType',
        context: TypeContext { mode: 'assert' } } } }
```

---

### What is the expected behaviour?
I was expecting the two arguments and the return type to be of  `StringType`, etc.

Also, the `name` of each argument is being set as `a` and `b` instead of the argument names.

From the [documentation](https://codemix.github.io/flow-runtime/#/docs/functions), it seems to imply that annotated functions should be well typed.

Is this a bug?

---

### Which package versions are you using?
* "babel-cli": "6.22.2",
* "babel-plugin-flow-runtime": "0.2.1"
* "flow-runtime": "0.2.1"

**Comment by phpnode** [comment]
@nunofgs you probably have `annotate` disabled in the plugin settings - if annotations aren't enabled you'll get a genericish function type because it's impossible for us to accurately infer the arguments or return type of functions which haven't been run yet. Also you're using `Number` and `String` instead of `number` and `string`.

**Comment by nunofgs** [comment]
@phpnode: This was my `.babelrc`:

```js
{
  "presets": [
    "es2015",
    "stage-0",
    "react"
  ],
  "plugins": [
    ["flow-runtime"]
  ]
}
```

The [documentation](https://codemix.github.io/flow-runtime/#/babel-plugin-flow-runtime) states that the _annotate_ default is `true`:

> annotate - Boolean, indicates whether object or function values that have type annotations should be annotated with those types at runtime. Defaults to true.

Indeed, when I explicitly set `annotate` to true it now correctly identifies types. Maybe something worth changing in the docs?
