### ISSUE TITLE
Add support for anonymous params in FunctionTypeAnnotations

### ISSUE THREAD

**Issue by bazyli-brzoska** [codemix/flow-runtime#44]
This is a:

 - [x] Bug Report

Which concerns:

 - [x] flow-runtime

---

### What is the current behaviour?

When encountering an untyped argument of a function, flow-runtime breaks:

```ts
export type Test = {
  test : (untypedArgument) => void,
}
```

With this unfortunate error:

```
Cannot read property 'name' of null
    at converters.FunctionTypeParam (babel-plugin-flow-runtime/lib/convert.js:590:29)
    at convert (babel-plugin-flow-runtime/lib/convert.js:38:16)
```

As soon as we add a type to `untypedArgument`:

```ts
export type Test = {
  test : (typedArgument : string) => void,
}
```

It compiles properly.

---

### Expected behavior

No Error or a better warning.

---

### Which package versions are you using?

0.2.1 (latest at the time of writing)

**Comment by phpnode** [comment]
This should be fixed in 0.3.0 which I'll release in an hour or so, it's worth noting though that the parameter is not _untyped_, it is _anonymous_ - `untypedArgument` will be treated as a type annotation itself, not the name of an argument.
