### ISSUE TITLE
Log warnings and continue, but do not throw for unimplemented features

### ISSUE THREAD

**Issue by bazyli-brzoska** [codemix/flow-runtime#45]
This is a:

 - [x] Bug Report

Which concerns:

 - [x] flow-runtime

---

### What is the current behaviour?

I'm unable to use `flow-runtime` on my codebase, because it throws errors on unsupported features, in turn breaking the whole application. Example:

```
Uncaught Error: Not implemented: acceptsType().
```

---

### What is the expected behaviour?

I think it would be better that instead of throwing it would log that a feature is currently unsupported (log, only optionally), and continue with the supported set of features.

Additionally it could be useful to point to the part of the code which uses the unsupported feature, since at the moment I'm unable to provide you with a specific example of where it breaks.

---

### Which package versions are you using?

flow-runtime 0.21

**Comment by phpnode** [comment]
Agreed, about to publish 0.3.0 which will fix this.

**Comment by bazyli-brzoska** [comment]
Thanks! You're too fast ;)

**Comment by bazyli-brzoska** [comment]
Few more throws are hardcoded, e.g. https://github.com/codemix/flow-runtime/blob/13e72fcc064bb6060c9ba49c58be3efe2f20ff40/packages/flow-runtime/src/TypeContext.js#L685

Although this is slightly unrelated (as these are assertions, as I understand), however I'm running with options: 
`{
          assert: false,
          annotate: true,
          warn: true
        }`

So I should still only get warnings here (otherwise the app doesn't even load).

**Comment by phpnode** [comment]
I thought about removing those but they should only happen in cases of programmer error - e.g. 

```js
t.object(t.property('a', t.string()); // ok
t.object(t.string()); // error
```

**Comment by bazyli-brzoska** [comment]
@phpnode sure, although it's hard to debug if they're causing my app not to load :(
I don't think it's a programmer error though cause FlowType checks and doesn't show any errors, so it might be a bug in `flow-runtime`. It would be great if no throws would ever happen if `assert: false`.

**Comment by phpnode** [comment]
The programmer making the error might be me! It would be awesome if you can post some code which replicates this
