### ISSUE TITLE
Default for assert not working correctly.

### ISSUE THREAD

**Issue by aocenas** [codemix/flow-runtime#48]
This is a:

 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [ ] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [ ] flow-runtime-validatosr
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

With config like this:
```
{
  "presets": [
    "react",
    "stage-2"
  ],
  "plugins": [
    "flow-runtime",
    "syntax-flow",
    "transform-flow-strip-types"
  ]
}
```
and NODE_ENV=development, assertions are not included in the generated code.

---

### What is the expected behaviour?

Assertions are included as stated by docs

---

### Which package versions are you using?

0.3.0

It works if the config is like this:
```
    ["flow-runtime", { "assert": "undefined" }],
```

It seems problem is here https://github.com/codemix/flow-runtime/blob/75630a4e64b5ceeb97be4f26b309f124a5047481/packages/babel-plugin-flow-runtime/src/createConversionContext.js#L18. It is checking whether `options.assert === 'undefined'` (notice the quotes), instead of `options.assert === undefined` (without quotes).

**Comment by phpnode** [comment]
fixed in 0.4.0
