### ISSUE TITLE
Website: try with async functions don't show error

### ISSUE THREAD

**Issue by christophehurpeau** [codemix/flow-runtime#58]
This is a:

 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [ ] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [x] The documentation website

---

Tested in [https://codemix.github.io/flow-runtime/#/try](https://codemix.github.io/flow-runtime/#/try):

```js
const foo = async (): Promise<number> => 'test';
foo().then(x => console.log(x));
```

with assertions enabled

### What is the current behaviour?

nothing is displayed

### What is the expected behaviour?

It should display an error ?

Note: it works with warnings and `test` is displayed if the return type is `Promise<string>`

**Comment by phpnode** [comment]
The error is being swallowed because the promise has not been resolved, this shows the error:
```js
const foo = async (): Promise<number> => 'test';
foo().then(x => console.log(x)).catch(e => console.error(e.message));
```
