### ISSUE TITLE
flow-runtime: Cannot resolve type: Buffer

### ISSUE THREAD

**Issue by ForbesLindesay** [codemix/flow-runtime#59]
This is a:

Bug Report

Which concerns:

flow-runtime

---

### What is the current behaviour?

code like:

```js
function foo(): Buffer {
  return getData();
}
```

produces:

```js
flowRuntime.ref('Buffer')
```

which results in the warning:

> flow-runtime: Cannot resolve type: Buffer

---

### What is the expected behaviour?

I would expect it to use `Buffer.isBuffer` or `instanceof Buffer` to check that the returned value is a buffer.

---

### Which package versions are you using?

0.5.0

**Comment by phpnode** [comment]
issue is we don't know if we're in node or the browser so we can't rely on `Buffer.isBuffer()` etc. For cases like this we have to rely on external type definitions via `flow-runtime-cli`. You should be able to generate definition files for your project using:

```sh
flow-runtime generate ./src > ./src/typedefs.js
```

which will spit out a file that includes a definition for `Buffer` and any other global types you're using. You can then include `typedefs.js` in your entry point.  It's fairly new though so please let me know if you find issues with it.

**Comment by phpnode** [comment]
hmm, on reflection i wonder if we should fall back to an instanceof check if we don't have a definition and we can find a global with that name.

**Comment by ForbesLindesay** [comment]
I think this problem is common enough that it should be handled automatically.  Generating a `typedefs` file seems like a significant extra complication.

The issue about `Buffer` applies to browserify as well as node.js.  I think it would probably be safe to assume that if the code has references to `Buffer`, then `Buffer` is probably going to be available.

The approach of falling back to instanceof checks against globals does seem sensible though.

**Comment by ForbesLindesay** [comment]
Thanks for the quick fixes.  Any chance of a release today?

**Comment by phpnode** [comment]
building it now

**Comment by phpnode** [comment]
v0.6.0
