### ISSUE TITLE
How would simple validations like min length work?

### ISSUE THREAD

**Issue by SukantGujar** [codemix/flow-runtime#6]
Does fr support them in any way at the moment?

**Comment by phpnode** [comment]
I need to add some docs for this, but yes:

```js
import t, {reify} from 'flow-runtime';
import type {Type} from 'flow-runtime';

type LongString = string;

const LongStringType = (reify: Type<LongString>);

LongStringType.addConstraint(input => {
  if (input.length < 3) {
    return 'must be at least 3 characters long';
  }
});

("this is fine": LongString);
("no": LongString); // throws
```

which translates to:

```js
import t, { reify } from "flow-runtime";
import { Type } from "flow-runtime";
const LongString = t.type("LongString", t.string());
const LongStringType = LongString;

LongStringType.addConstraint(input => {
  if (input.length < 3) {
    return "must be at least 3 characters long";
  }
});

LongString.assert("this is fine");
LongString.assert("no");
```

**Comment by SukantGujar** [comment]
How about this instead:
```js
const LongString = t.type("LongString", 
        t.string().minLength(3, "must be {minLength} characters long"));
```

Or -
```js
LongStringType.addConstraints(
    compose(t.v.minLength(3, "must be {minLength} characters long"))),
         t.v.maxLength(300, "must be less than {maxLength} characters"))));
```

Basically, have a list of common validator methods available on types, or compose them together into one validators chain. Every validator method can be a curried function of this syntax -
```js
minLength = R.curry((minLength,
    errorTemplate = "The value must be at least {minLength} characters in length.", value) => (
        R.size(value) < minLength ? templateToString(errorTemplate, minLength)) : null
);
```

I am not sure how this should be represented by the corresponding flow syntax, but may be an extended syntax could look like -

```js
type LongString = compose(string, minLength(3, "must be {minLength} characters long"))
```

**Comment by phpnode** [comment]
We can't do anything which changes the syntax because we need to maintain compatibility with Flow and unfortunately it will choke on things like `type foo = bar();`.

I'm not sure about adding methods like `minLength()` to the types themselves - you always end up needing custom validators so I think it's nicer to have a way to compose validators to create a new type (or patch an existing one where required). Something like this:

```js
import t from 'flow-runtime';
import {minLength, onlyLowercase} from 'flow-runtime-validators';

const SomeStringType = t.compose(
  t.string(),
  minLength(3),
  onlyLowerCase
);

SomeStringType.validate("yes");
SomeStringType.validate("NO");
```

**Comment by phpnode** [comment]
I added [flow-runtime-validators](https://codemix.github.io/flow-runtime/#/flow-runtime-validators) and some docs for type refinements here: https://codemix.github.io/flow-runtime/#/docs/type-refinements

**Comment by SukantGujar** [comment]
Is there a way to add constraints to a type being inferred from a `class`? We are having existing classes for our models and would like to add constraints over them, instead of having to write types.

Off-topic, could you explain to me what `reify` does?

**Comment by phpnode** [comment]
@SukantGujar there will be when #22 is fixed, will get to it soon.

`reify` is used to turn a static type into a runtime type without flow itself complaining, for example:

```js
type Foo = string;
const FooType = Foo; // flow errors here because you're referencing a Type not a Value.
```
What we want to do is to be able to refer to `Foo` by name without flow errors, and ideally we'd like to propagate the type too, so we should be able to tell flow that `FooType` is a `Type<string>`.

`reify` is a magic value (actually it's non existent and only exists at compile time) that can work around the problem, with the following:
```js
import {reify} from 'flow-runtime';
import type {Type} from 'flow-runtime';

type Foo = string;

const FooType = (reify: Type<Foo>); // no errors

console.log(FooType); // no errors
``` 

This lets flow receive the correct type for `FooType` and won't throw any errors about referencing types as values.

The babel plugin just translates this into:

```js
import t from 'flow-runtime';
const Foo = t.string();

const FooType = Foo;
console.log(FooType); 
```

**Comment by STRML** [comment]
@phpnode Similar to https://github.com/gcanti/babel-plugin-tcomb#runtime-type-introspection, yeah? Your syntax looks a lot nicer.

**Comment by phpnode** [comment]
@STRML yes it's very similar to how tcomb does it, actually Giulio and I had a conversation around tcomb and flow-io where we discuss the similarities / goals here - https://github.com/gcanti/flow-io/issues/19

**Comment by phpnode** [comment]
added a few docs here - https://codemix.github.io/flow-runtime/#/docs/working-with-flow
