### ISSUE TITLE
Add FLOW_RUNTIME=namespace configuration

### ISSUE THREAD

**Issue by gajus** [codemix/flow-runtime#64]
This is a:

 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

The current implementation of `babel-plugin-flow-runtime` allows configuration that either inlines the assertions or skips them at a compile them. This is good enough for developing a library that uses flow-runtime.

```js
const add = (a: number, b: number): number => a + b;

```

is transformed to:

```js
import t from 'flow-runtime';
const add = (a, b) => {
  let _aType = t.number();
  let _bType = t.number();
  const _returnType = t.return(t.number());
  t.param('a', _aType).assert(a);
  t.param('b', _bType).assert(b);
  return _returnType.assert(a + b);
};

```

However, it limits library author's ability to distribute code with flow-runtime assertions. I do not want to use dependencies in production that have inlined flow-runtime assertions (for performance reasons).

---

### What is the expected behaviour?

I'd like `babel-plugin-flow-runtime` to accept a configuration that inlines a conditional runtime assertion, e.g.

```json
{
  "plugins": [["flow-runtime", {
    "assert": "applaudience:showtime-api"
  }]]
}
```

would produce code:

```js
import t from 'flow-runtime';
const add = (a, b) => {
  if (process.env.FLOW_RUNTIME && process.env.FLOW_RUNTIME.startsWith('applaudience:showtime-api')) {
    let _aType = t.number();
    let _bType = t.number();
    const _returnType = t.return(t.number());
    t.param('a', _aType).assert(a);
    t.param('b', _bType).assert(b);
    return _returnType.assert(a + b);
  } else {
    return a + b;
  }
};

```

> This is a mock implementation. A real-life implementation would follow the [`debug`](https://www.npmjs.com/package/debug) conventions.

This way, I could distribute all my codes with inlined `flow-runtime` assertions that users could enable when debugging issues the same way that [`debug`](https://www.npmjs.com/package/debug) is being used, e.g.

```bash
FLOW_RUNTIME=applaudience:* node ./index.js

```

would enable runtime type assertions for all dependencies under the "applaudience" namespace.

---

**Comment by phpnode** [comment]
I'd like this ability too but I'm not sure this is the right solution. The problem is that the guards aren't free and it still increases the code size a lot (DCE can help with this of course), also it means the implementation of babel-plugin-flow-runtime will get a lot more complicated. 

I think a better solution is to ship two versions of the library, one with assertions turned off, and switch between them in the entry point to the lib, 

```js
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./lib');
}
else {
  module.exports = require('./lib-checked');
}
```

This way you never have to pay the cost for assertions you're not using. However I'm not sure this is the perfect solution either.

**Comment by gajus** [comment]
> I think a better solution is to ship two versions of the library, one with assertions turned off, and switch between them in the entry point to the lib,

Not sure how'd you achieve that...

Regarding file size, it is absolutely irrelevant in the context of Node.js. It gets trickier with the client-side codes, but as you said yourself, thats the role of the GCE to remove the dead code. In fact, I am pretty sure webpack could do it in this case (static condition) too.

> also it means the implementation of babel-plugin-flow-runtime will get a lot more complicated.

What would make it a lot more difficult?

I am not familiar with the current code base. Therefore, I am not in position to comment about the complexity of the implementation.

**Comment by phpnode** [comment]
> Not sure how'd you achieve that...

With a single conditional require at the entry point to the lib, but obviously this only works in simple cases, not for specific file imports, e.g. `import Foo from 'bar/foo'` wouldn't work.

> What would make it a lot more difficult?

Hard to explain I guess, it just means that we'd need to keep track of a lot more state and be a bit smarter about the transformations we're doing, e.g. right now if you annotate a class we modify the constructor quite a bit, and those modifications take place in different sections within the constructor body to respect TDZ, super etc. For this change we'll need to introduce this check several times in the constructor. Similarly we rely on scoping rules that allow us to simply replace types with values and have everything just work, this change would require hoisting variable declarations upwards.

These problems aren't unsurmountable, I would just like to avoid them if possible. I would even prefer generating output like this:

```js
if (process.env.FLOW_RUNTIME && process.env.FLOW_RUNTIME.startsWith('applaudience:showtime-api')) {
   
  import t from 'flow-runtime'; // we'd need to figure out how to deal with this problem
  const add = (a, b) => {
    let _aType = t.number();
    let _bType = t.number();
    const _returnType = t.return(t.number());
    t.param('a', _aType).assert(a);
    t.param('b', _bType).assert(b);
    return _returnType.assert(a + b);
  };
}
else {
  const add = (a, b) => a + b;
}
```

**Comment by gajus** [comment]
> With a single conditional require at the entry point to the lib, but obviously this only works in simple cases, not for specific file imports, e.g. import Foo from 'bar/foo' wouldn't work.

I was referring to the build process. I am sure it is doable. Come to think about it, not even complicated. Yet, would require maintaining two distinct builds, which in itself is another opportunity for a human error.

> Hard to explain I guess, it just means that we'd need to keep track of a lot more state and be a bit smarter about the transformations we're doing, e.g. right now if you annotate a class we modify the constructor quite a bit, and those modifications take place in [..]

You could do the transformation outside of the function body, i.e. you could conditionally redeclare the function, e.g. if we start with

```js
const add = (a: number, b: number): number => a + b;

```

then we could transform it to:

```js
const add = process.env.FLOW_RUNTIME && process.env.FLOW_RUNTIME.startsWith('applaudience:showtime-api') ? add1 : add0;

const add0 = (a, b): number => a + b;

const add1 = (a, b) => {
  let _aType = t.number();
  let _bType = t.number();
  const _returnType = t.return(t.number());
  t.param('a', _aType).assert(a);
  t.param('b', _bType).assert(b);
  return _returnType.assert(a + b);
};

```

**Comment by gajus** [comment]
> These problems aren't unsurmountable, I would just like to avoid them if possible. I would even prefer generating output like this:

Oh, lol. I finished reading your comment after composing my suggestion. At least we agree on an alternative approach. :-)

**Comment by phpnode** [comment]
>  At least we agree on an alternative approach. :-)

I even wonder if this could be an entirely separate plugin - a plugin that takes a set of babel plugins and applies them in one branch of a conditional and not in another.

**Comment by phpnode** [comment]
here we go: https://github.com/codemix/babel-plugin-conditional

**Comment by gajus** [comment]
Interesting. Well done @phpnode

**Comment by Amin-Medbelle** [comment]
@phpnode Have you seen [this article](https://www.jonathan-petitcolas.com/2017/02/23/different-babel-configuration-with-single-babelrc-file-using-babelenv.html)?
It pretty much resolves the conditional plugin issues.
