### ISSUE TITLE
Failed to reveal type in Temporal Dead Zone.

### ISSUE THREAD

**Issue by FredyC** [codemix/flow-runtime#69]
This is a:

 - [x] Question

Which concerns:

 - [x] flow-runtime

---

### What is the current behaviour?
The message is popping in the console when my app starts. It's probably not an error as app seems to be working, but I am curious if it's normal.

**Comment by phpnode** [comment]
you are possibly doing something like this:

```js
import type {Foo} from 'somelib';
```

And `Foo` can't be resolved, i.e. it's undefined. This can happen if you're using flow typed definitions which will work with flow but not always with flow-runtime. I'd like to improve the error message because it's hard to tell exactly which type is causing the problem.

**Comment by phpnode** [comment]
Error message should now indicate the type causing the problem, released in 0.9.1

**Comment by FredyC** [comment]
So I have updated to 0.10.0 now and now I am just getting the fallback message "Failed to reveal unknown type in Temporal Dead Zone". Any hints how to hunt these down?

**Comment by FredyC** [comment]
Ok, I got it. Apparently there is a problem using export extensions. I like the idea of having every reusable type in a separate file in a folder. Then I like to add `index.js` which gathers them all together and exports.

```
export type { Billing } from './Billing'
export type { ChargeStatus } from './ChargeStatus'
export type { Cuid } from './Cuid'
export type { RequestContext } from './RequestContext'
export type { Shop, PublicShop, PrivateShop } from './Shop'
export type { Transaction } from './Transaction'
```

Doing it like this is failing with those message. Transforming to separate import and export works correctly. Wondering if it's actual issue of the `transform-export-extensions` plugin.

**Comment by gufy** [comment]
I understand that this issue might appear when Importing library flow typed definitions (e.g. type $Request from express). 

Is there a way around this? Any of following:
 - Is there a way how to suppress errors related to ./flow-typed/npm folder?
 - What is actually wrong with the flow typed definition? Is there a way how this can be fixed by changing the definition script?

**Comment by phpnode** [comment]
For scenarios where you're importing types from libdefs, the best answer is to use `flow-runtime-cli` to extract those types into another file:
```sh
flow-runtime-cli generate ./src > ./src/typedefs.js
```
then in your entry point:
```js
import './typedefs';
```

**Comment by bsmith-cycorp** [comment]
@phpnode I tried using your solution, but all I ended up getting was the same error in the command line instead of the browser console...

I'm also not doing any weird import-reexport stuff, so I don't know what the deal is. It seems like just importing any type at all causes this problem.

**Comment by bsmith-cycorp** [comment]
Here's my import:
```
import type { QuerySpec, InferenceParameterSpec, Inference, KBContentTestConstraints } from 'lib/js/types/Queries';
```
Here's Queries.js:
```
export type InferenceParameterSpec = InferenceParameterSpecBoolean |
                                      InferenceParameterSpecNumber |
                                      InferenceParameterSpecChoice

type InferenceParameterSpecBase = {|
  foo: string,
  keyName: string,
  label: string,
  debugParam: boolean,
  dynamic: boolean,
  type: 'boolean'|'number'|'choice',
  inferenceDefault: string|boolean,
  browserDefault?: string|boolean,
  hint: string,
  section?: string,
|}

export type InferenceParameterSpecBoolean = {
  ...InferenceParameterSpecBase,

  type: 'boolean'
}

export type InferenceParameterSpecNumber = {
  ...InferenceParameterSpecBase,

  type: 'number',
  unboundedToken?: Array<any>|string,
  numberConstraints: Array<{
    min?: number,
    max?: number,
    integerOnly?: bool
  }>
}

export type InferenceParameterSpecChoice = {
  ...InferenceParameterSpecBase,

  type: 'choice',
  options: Array<{
    "label": "string",
    "value": "string"
  }>
}
```

So I am using a union type and a spread, but I haven't seen anybody mention either of those as being part of the problem. Honestly this makes `flow-runtime` useless for me until it's figured out, as imported types make up ~80% of the things I want to check at runtime.

**Comment by bsmith-cycorp** [comment]
Update: it turned out I didn't have `// @flow-runtime enable` on my separate type files themselves
