### ISSUE TITLE
Return values of Promises are not checked in runtime

### ISSUE THREAD

**Issue by niieani** [codemix/flow-runtime#71]
This is a:

 - [x] Bug Report

Which concerns (not really sure):

 - [x] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [x] flow-runtime-validators

The following code does not raise any errors:

```ts
type Person = {
  name: string
}

function untrustedEndpoint(id: string): Promise<{ data: Person }> {
  return Promise.resolve(null) // <= wrong
}

untrustedEndpoint('id')
```

Currently we will only get the type assertion error once another function receives the return value as an argument, so a workaround is to:

```ts
type Person = {
  name: string
}

type Endpoint = { data: Person }

function untrustedEndpoint(id: string): Promise<Endpoint> {
  return Promise.resolve(null) // <= wrong
}

function processPersonNameFromEndpoint(response : Endpoint) {
  return response.data.name
}

untrustedEndpoint('id').then(processPersonNameFromEndpoint)
```

Raised by @gcanti at https://github.com/gcanti/io-ts/issues/4#issuecomment-285756198

**Comment by phpnode** [comment]
Issue here is that we don't know the inner value of a promise because it hasn't resolved yet. I did consider adding a handler like this:
```js
return Promise.resolve(null).then(value => Endpoint.assert(value));
```
But it adds an extra tick to every promise resolution so I didn't implement it, I'd be open to doing so if there's demand. 
In practice _most_ code that uses flow is probably going to also use `async`/`await` and that doesn't suffer from this problem:
```
async function untrustedEndpoint(id: string): Promise<Endpoint> {
  const data = await fetch(someURL);
  return data; // will throw if not an Endpoint
}
```

**Comment by niieani** [comment]
Good point about the extra tick. However, should the promise validation be optional, I don't think this will be a big problem. In our case we'd only use `flow-runtime` when developing or debugging, never in production, so the extra tick wouldn't matter.

**Comment by phpnode** [comment]
We can also skip this check in almost all cases in `async` functions - we'd only need it in the fairly rare case of returning a promise, ok, will add it.

**Comment by phpnode** [comment]
ok, the fix works in this scenario - where you're returning something that is definitely a promise, but does not solve it in the general case, e.g. if you have a zalgo function that returns something like `Foo | Promise<Foo>` we won't insert the check there, nor will it insert a check if you cast a variable to a promise or use a promise as a parameter to a function - that requires too much work to get right and I don't think it's really worth it. 

Released in 0.9.0

**Comment by niieani** [comment]
Not sure if returning a promise really is such a rare case (sometimes it's superior than using async/await), but I understand where you're coming from. Thanks!

**Comment by phpnode** [comment]
> Not sure if returning a promise really is such a rare case (sometimes it's superior than using async/await), but I understand where you're coming from. Thanks!

I just mean in async function specifically:

```js
async function foo (): Promise<string> {
  await bar();
  return Promise.resolve(null); // no inner type check here, but you'd usually await anyway
}
```

This does get a check:

```js
function foo (): Promise<string> {
  return Promise.resolve(null); // throws
}
```
