### ISSUE TITLE
React$Element support

### ISSUE THREAD

**Issue by anru** [codemix/flow-runtime#76]
This is a:

 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

```jsx
import React, { Element } from 'react';

class Foo extends React.Component {
  render(): Element {
    return <div>hello world</div>;
  }
}
```

This code doesn't work correctly at runtime, because there is no "Element" exported in react package.
But for flow itself it's valid construction.

**Comment by phpnode** [comment]
To handle this kind of thing you'll have to use flow-runtime-cli - the following will crawl your source code, find all the external types you're using (like `React$Element`), discover their Flow definitions and dump the `flow-runtime` definitions into a file that you can then import at the start of your entry point:

```
npm install --dev flow-runtime-cli
flow-runtime generate ./src > ./src/typedefs.js
```

Now import `typedefs.js` once, at the entry point to your application. `flow-runtime` will then be able to understand these external types.
