### ISSUE TITLE
Support $Exact

### ISSUE THREAD

**Issue by dapetcu21** [codemix/flow-runtime#78]
This is a:

 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

Currently, the following code issues flow warnings, yet flow-runtime accepts it:

```
type T = $Exact<{
  a: number
}>

function f (t: T) {
  console.log(t);
}

f({
  a: 12,
  b: 'Should not be here',
});
```

---

### What is the expected behaviour?

For flow-runtime to check for additional fields in objects when `$Exact<T>` is used.

---

### Which package versions are you using?

babel-plugin-flow-runtime 0.10.0

**Comment by phpnode** [comment]
In the mean time, you can use exact object syntax:

```js
type Foo = {|
 only: 'this prop'
|};
```

**Comment by dapetcu21** [comment]
Cool! I was not aware of that syntax. Still learning Flow.
