### ISSUE TITLE
Error when extending generic class

### ISSUE THREAD

**Issue by tibdex** [codemix/flow-runtime#79]
Hi!

This is a:

 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

I have the following code:

```typescript
class Container<T> {
  constructor(value: T) {
    console.log(value);
  }
}

class StringContainer extends Container<string> {
  // Nothing more
}
```

Then this line is ok:

```typescript
const instance: Container<string> = new StringContainer('str');
```

But this one:

```typescript
const Klazz: Class<Container<string>> = StringContainer;
```

raises the error:

>Value must be a Class of Container<string>
>
>Expected: Class<Container<string>>
>
>Actual: StringContainer

---

### What is the expected behaviour?

I would expect `flow-runtime` not to raise any error as this is [valid code according to Flow](https://flowtype.org/try/#0MYGwhgzhAEDCD2A7ALmAlogpgJwDwBUA+aAbwChppgkJlsBXYZebACgDcwR7MAuafAEpSFSlRrwQmAHQh4Acw5ceggNyiAvmS1lQkGAGU6GeQhTos2aJgAeyTIgAmMM6gw5ctbCeLlKAen9oADl4ZAALE2gAWxZMbTJdGmRoDFowRGA+OCQ3S09jRHliAF5oLAB3aCNvItcLHFYAci8mtSTEWmgAaXAALz7+WHAoXHr3PC8fUurC01yG7FUgA).

Do you have any idea of how we can make this work ?

Thanks a lot :)

---

### Which package versions are you using?

`v0.10.0`

**Comment by phpnode** [comment]
fixed in 0.11.1
