### ISSUE TITLE
Question babel-plugin-flow-runtime: overwrite assert: false

### ISSUE THREAD

**Issue by RainerAtSpirit** [codemix/flow-runtime#8]
According to the documentation assert: true should be turned off during production builds.

For an UMD library with an public API it would be beneficial if assertions could be scoped to specific public methods. That would allow getting the the benefits of run time type checking for the library consumer without getting the overall performance penalty.

Here's an example, where I'd like to get assertions for the public `filter` method (taken from a tcomb babel-plugin-transform-flow-strip-types implementation).

```javascript
...
const FilterLogic = enums.of(['or', 'and'], 'FilterLogic')

type FilterExpression = {
  field: string,
  operator: string,
  value: any
}

type FilterGroup = {
  logic: FilterLogic,
  filters: Array<FilterExpression | FilterGroup>
}

export default class Collections {
...

// Would it be possible to turn on assertion for .filter?
// maybe by using a decorator like @guarded?
  filter (options?: FilterGroup) {
    if (!options) {
      return toJS(this.$filter)
    }
    this.$filter = options
    this.data = []

    return this.read()
  }
...
}


```

**Comment by phpnode** [comment]
I love this idea, I'm not quite sure how it should be done though. In `babel-plugin-typecheck` we used special comments but I don't really like that, I wonder if it should be a block-level directive, a bit like `"use strict"`:

```js
"use types";

export function demo (a: string): string {
  return a;
}
```

and 

```js
export function foo (a: string): string {
  return a; // no assertions
}
export function bar (a: string): string {
  "use types"; 
  return a; // asserts
}
```

**Comment by RainerAtSpirit** [comment]
I've no idea how this should be done either ;-), but it sounds like using block level directives would allow to get the job done on a all or nothing base.
e.g. in the example below all Collection methods (that form the public API) would perform run-time asserts, correct?

```javascript

export default class Collections {
  "use types";

  filter...
  sort...
  read...
...
}
```

**Comment by phpnode** [comment]
This would actually be a syntax error because the class body isn't a block, you're right that this approach would not let you preserve checks for certain properties, it'd only work for methods or the whole class

**Comment by phpnode** [comment]
Added pragma like `// @flow-runtime assert, decorate` and suppression types / comments in v0.0.7, docs here - https://codemix.github.io/flow-runtime/#/docs/pragmas

**Comment by RainerAtSpirit** [comment]
This looks excellent. Thanks for adding.
