### ISSUE TITLE
Handling of default Redux actions

### ISSUE THREAD

**Issue by jwoldan** [codemix/flow-runtime#80]
This is a:

 - [ ] Bug Report
 - [ ] Feature Request
 - [x] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

We are attempting to use [disjoint unions](https://flowtype.org/blog/2015/07/03/Disjoint-Unions.html) to strongly type our Redux reducer actions.  The problem that occurs is that Redux sends several default actions through all reducers at initialization specifically including:

```js
{ type: "@@redux/INIT" }
{ type: "@@INIT" }
{ type: "@@redux/PROBE_UNKNOWN_ACTION_8.q.v.z.d.o.8.y.f.o.1.4.r.d.z.b.m.x.6.r" }
```

For the last action, the latter part of the string is a randomized set of characters so it cannot be strongly typed, and by adding a type such as `{ type: string }` to our disjoint union of actions, we lose the guarantee that a specific action type will have a specific payload.  If we do not add types for these actions, we receive a type error from the runtime.

This issue has come up with other type-checking runtimes (See https://github.com/reactjs/redux/issues/792), however I have not been able to find any discussion of this issue in relation to flow-runtime.  Are there any known workarounds for this issue?

---

### What is the expected behaviour?

Ideally there would be a way to either ignore or specifically add types for these default Redux initialization actions.

---

### Which package versions are you using?

0.10.0

**Comment by phpnode** [comment]
There is a bit of a challenge here because the ideal solution would still let Flow catch the errors statically. I can think of a fairly ugly solution that should work: Create a union type which approximates the cases you're looking to deal with, then add a type to that union at runtime, e.g.:

```js
import t, {reify} from 'flow-runtime';
import type {Type} from 'flow-runtime';

type ReduxInternalActionType
  = '@@redux/INIT'
  | '@@INIT'
  ;

const ReduxProbeUnknownActionType = t.refinement(t.object({type: t.string()), input => {
  if (!/^@@redux\/PROBE_UNKNOWN_ACTION/.test(input.type)) {
    return 'can only be a redux probe unknown action';
  }
});

(reify: Type<ReduxInternalActionType>).type.types.push(ReduxProbeUnknownActionType);

type ReduxInternalAction = {
  type: ReduxInternalActionType;
};

type ReduxCustomAction = {
  type: 'your' | 'actions' | 'here'
}

type ReduxAction = ReduxInternalAction | ReduxCustomAction;

function reducer (state: State, action: ReduxAction) {
  ...
}
 
```

**Comment by jwoldan** [comment]
Thank you!

**Comment by Meeeeow** [comment]
@jwoldan Maybe use `https://github.com/acdlite/redux-actions` better than use switch with ugly patch
