### ISSUE TITLE
Async / Await ?

### ISSUE THREAD

**Issue by FredyC** [codemix/flow-runtime#81]
This is a:

 - [x] Bug Report

Which concerns:

 - [x] flow-runtime

---

### What is the current behaviour?

I have this function which accepts callback with specified argument type. The callback is usually async function.
```js
function RequestQueue({ requestDone: (ctx: RequestContext) => any }) {
}
// somewhere else...
const requestDone = async (ctx: RequestContext) => {
    await doSomeAsyncStuff()
}
RequestQueue({ requestDone })
```

> RuntimeTypeError: requestDone argument "ctx" must be: RequestContext
> Expected: (ctx: RequestContext) => any
> Actual: (ctx: RequestContext) => any
---

### What is the expected behaviour?

I can imagine this is probably bleeding edge stuff, but wanted to record this in here for some future reference. It's possible it this be actually solved with native support for async/await. With transpilation in place it's probably impossible task.

---

### Which package versions are you using?

NodeJS v6.10.1

>     "babel-plugin-flow-runtime": "^0.10.0",
>     "babel-plugin-syntax-flow": "^6.18.0",
>     "babel-plugin-transform-decorators-legacy": "^1.3.4",
>     "babel-plugin-transform-flow-strip-types": "^6.22.0",
>     "babel-preset-latest-minimal": "^1.1.2",
>     "babel-preset-stage-1": "^6.22.0",
>

**Comment by phpnode** [comment]
Hmm this should work, please would you add the definition for `RequestContext` to your example code, and also the signature for `RequestQueue` looks wrong?

**Comment by FredyC** [comment]
```js
export type RequestContext = {
	requestId: Cuid,
	payload: string|Object,
	meta: Object,
	state: ?Object,
	error: ?string,
};
```

Not sure what you mean by that _signature for RequestQueue looks wrong_, can you elaborate?

Either way if I look at the transpiled code I think it's obvious why it cannot work...

```js
const requestQueue = RequestQueue({ requestDone: _flowRuntime2.default.annotate((() => {
		var _ref = _asyncToGenerator(function* (ctx) {
			let _ctxType = _flowRuntime2.default.ref("RequestContext");

			_flowRuntime2.default.param("ctx", _ctxType).assert(ctx);

			yield doSomeAsyncStuff();
		});

		return function (_x) {
			return _ref.apply(this, arguments);
		};
	})(), _flowRuntime2.default.function(_flowRuntime2.default.param("ctx", _flowRuntime2.default.ref("RequestContext")))) });
```

Since there is an IIFE and returning a `function (_x) {...` it's apparent that it indeed has a wrong signature. Maybe I am missing something here...

**Comment by phpnode** [comment]
The following is not valid syntax:
```js
function RequestQueue({ requestDone: (ctx: RequestContext) => any }) {
}
```
The annotation is in the wrong position, it needs to be written like this instead:
```js
function RequestQueue({requestDone}: { requestDone: (ctx: RequestContext) => any }) {
}
```

When I make this change and try it on the docs site it seems to work correctly

**Comment by FredyC** [comment]
Oh I am sorry, I wanted to make more concise example and lost true value in it. Here is the real one that doesn't work. The callback is alone there as a second argument.

```js
function RequestQueue({ wares }: Options, requestDone: (ctx: RequestContext) => any) {
}

const requestQueue = RequestQueue({ wares }, async (ctx: RequestContext) => {
}
```

**Comment by phpnode** [comment]
The following code seems to work for me on /try, can you modify it so that it breaks? (please include all the code :) )

```js

export type RequestContext = {
	requestId: Cuid,
	payload: string|Object,
	meta: Object,
	state: ?Object,
	error: ?string,
};

type Options = {wares: {}};
const wares = {}

function RequestQueue({ wares }: Options, requestDone: (ctx: RequestContext) => any) {
  console.log('yo');
}

const requestQueue = RequestQueue({ wares }, async (ctx: RequestContext) => {
  
});
```

**Comment by FredyC** [comment]
@phpnode Well this code as a whole indeed works, however once I split it into separate files (as in my original code) it explodes... Here is the gist of how I've split it: https://gist.github.com/FredyC/05e980406416cf64f481dc4f8cd677a3

It did not matter when I've separated types only to a file, it worked well there. But with 3-way separation it almost looks like that imported RequestContext is different in both files.

**Comment by FredyC** [comment]
I've investigated bit with a debugger. In a transpiled main.js, there is this line I am not sure what it's supposed to do.

`const RequestContext = _flowRuntime2.default.tdz(() => _types.RequestContext);`

Input value is correct...

![image](https://cloud.githubusercontent.com/assets/1096340/24582121/206edd1a-1729-11e7-98f0-39e08029f3a0.png)

...but the result yields something unknown...

![image](https://cloud.githubusercontent.com/assets/1096340/24582125/3705949c-1729-11e7-8797-880a5018d119.png)

**Comment by phpnode** [comment]
@FredyC thanks for digging into this, I can now replicate using:
```js

type Options = {wares: {}};
const wares = {}

function RequestQueue({ wares }: Options, requestDone: (ctx: RequestContext) => any) {
  console.log('yo');
}

const param = async (ctx: RequestContext) => {
  
}

export type RequestContext = {
	requestId: Cuid,
	payload: string|Object,
	meta: Object,
	state: ?Object,
	error: ?string,
};

const requestQueue = RequestQueue({ wares }, param);
```
