### ISSUE TITLE
Can you provide a build generated with transform-runtime?

### ISSUE THREAD

**Issue by bluepnume** [codemix/flow-runtime#82]
My situation is this:

- I'm running my tests with karma + babel + babel-runtime
- I'm not using polyfills because I want to be closer to my live environment
- I'm not using transform-runtime for the same reason

It'd be great if there was a version of flow-runtime built/distributed with transform-runtime, which loads in things like regenerator and WeakMap specifically for the flow-runtime module only. Then I can continue to exclude polyfills from my tests, and know that my tests will fail if I try to use `WeakMap` or something not available in older browsers I have to support.

Thoughts on this?

**Comment by phpnode** [comment]
We're already producing 3 builds (umd, es2015 and commonjs), I don't really want to include another - if you're using webpack you could always produce another target which only includes flow-runtime and the various transforms / polyfills it needs, so your normal code won't be affected

**Comment by bluepnume** [comment]
Hi @phpnode. Totally understand you're reasoning, there are a lot of builds already. 

One thing I need to figure out is, right now I'm running `flow-runtime` as a babel plugin, and I'm not sure how I'd apply polyfills or transform-runtime to just this module and ignore the rest of my code. Do you have any tips there?

Second quick question -- is there a reason the existing 3 builds couldn't be passed through transform-runtime, without creating an additional build? That way the builds would be es5-ready out of the box.

Appreciate your time, and really love flow-runtime! You're doing awesome work on this thing and it's saved us several times already.

**Comment by phpnode** [comment]
I would do something like this:
```sh
cat node_modules/flow-runtime/dist/flow-runtime.js | babel --no-babelrc --presets=env,stage-0,react --plugins=transform-decorators-legacy,transform-runtime > rt.js
```

I get your point about wanting an ES5 build, the issue is that with all of the dependencies the lib becomes huge, and if they're included directly within flow-runtime then any other code which uses symbols or weakmaps or any other feature will need to duplicate the polyfill code - for this reason I think we have to ship modern code and let the consumer deal with this as appropriate for their environment.

**Comment by bluepnume** [comment]
Hey again,

Totally get your reasoning. I'd say the duplication is less of an issue since I'm imagining (?) most people are using this in their testing env rather than for distributed code.

Pre-transcompiling `flow-runtime.js` makes perfect sense -- but then how do I get my pre-compiled version to be picked up by the `flow-runtime` babel plugin?

**Comment by phpnode** [comment]
> Pre-transcompiling
😄 

> how do I get my pre-compiled version to be picked up by the flow-runtime babel plugin?

Yeah, that's true, now you'd need to do some rewiring. `babel-plugin-flow-runtime` should accept a `libName` configuration option to point to the right file or module (we'd need this even if we do end up shipping a batteries included build too)

**Comment by bluepnume** [comment]
Sounds good to me!

**Comment by phpnode** [comment]
I caved and now regenerator-runtime comes bundled as of 0.11.1, thanks to @ForbesLindesay
