### ISSUE TITLE
How to use flow-runtime with JSON Schema

### ISSUE THREAD

**Issue by tonyxiao** [codemix/flow-runtime#85]
The documentation website says that flow-runtime can be converted to other representations, such as JSON Schema. However there is no example / explanation for how it is actually done. Can you provide a bit more information here?

This is a:

 - [ ] Bug Report
 - [ ] Feature Request
 - [x] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [x] The documentation website

**Comment by phpnode** [comment]
there's an issue for it, #23 - I've made some progress on it on a branch but i've got no time at the moment
