### ISSUE TITLE
What exactly does t.annotate do?

### ISSUE THREAD

**Issue by tonyxiao** [codemix/flow-runtime#86]
When annotation mode is turned on

This
```
function printThing(thing: string) {
}
```

becomes
```
import t from "flow-runtime";
function printThing(thing) {}
t.annotate(printThing, t.function(t.param("thing", t.string())));
```

However while I totally understand what `warn` and `assert` does, I can't seem to find any docs on just what `t.annotate` actually do. Can someone help me point me to the right place to look?

**Comment by phpnode** [comment]
it adds a special symbol to the value recording the type of that value, you can then retrieve it like this:
```js
const annotation = t.getAnnotation(printThing);
console.log(annotation.toString());
annotation.assert(someOtherFunction);
```

flow-runtime uses this when validating things like functions which are otherwise impossible to validate (without running them).

**Comment by tonyxiao** [comment]
I see. @phpnode is it a requirement to turn `annotate` on if you want to use either `warn` or `assert`? Is it a valid use case to turn annotate off but turn assert on?

**Comment by phpnode** [comment]
No it should work without it, but the checks will be less strict in some cases

**Comment by tonyxiao** [comment]
Got it. So the value of annotation is stricter check during `warn` and `assert`. So if you want the most comprehensive validation you should turn it on, and if you aren't warning or asserting you should leave it off. Is there any use case for having `annotate` on without either `warn` or `assert`?

**Comment by phpnode** [comment]
If you want to expose your types as values in some way, to allow e.g. `SomeType.assert(foo)` then leaving annotate on will give the best results, the same is true if you're using the [pattern matching](https://codemix.github.io/flow-runtime/#/docs/pattern-matching) features.

**Comment by tonyxiao** [comment]
Can you give a single example where having annotation allows you to validate something that otherwise do not get validated?

**Comment by phpnode** [comment]
```js
type StringMaker = (id: string) => string;

function makeNumber (id: number): number {
 return id; 
}

const fn: StringMaker = makeNumber; // fails when annotate is on, passes when off.
```
