### ISSUE TITLE
React.Component's 'props' cannot be of type $FlowFixMe

### ISSUE THREAD

**Issue by niieani** [codemix/flow-runtime#90]
This is a:

 - [x] Bug Report

Which concerns:

 - [x] babel-plugin-flow-runtime

---

### What is the current behaviour?

Defining the type of `props` as `$FlowFixMe` causes an error to be thrown (even in assert mode).

---

### What is the expected behaviour?

No error, and no assertion should be set.

---

### Which package versions are you using?

0.10.0

**Comment by phpnode** [comment]
fixed in 0.11.1
