### ISSUE TITLE
Assigning wrong values in object

### ISSUE THREAD

**Issue by nionis** [codemix/flow-runtime#96]
This is a:

 - [ ] Bug Report
 - [ ] Feature Request
 - [ x] Question
 - [ ] Other

Which concerns:

 - [x ] flow-runtime
 - [x ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

Paste this code [here](https://codemix.github.io/flow-runtime/#/try)
```javascript
var x: { y: boolean } = { y: true };

x.y = "hello";

console.log(x.y);
```

### What is the current behaviour?
This is transformed to:
```javascript
import t from "flow-runtime";
var _xType = t.object(t.property("y", t.boolean())),
    x = _xType.assert({ y: true });

x.y = "hello";

console.log(x.y);
// prints 'hello'
```

---

### What is the expected behaviour?
When boolean y in object x is assigned to a non-boolean value, according to flow it should error out:
```bash
inconsistent use of library definitions
  3: x.y = "hello";
           ^^^^^^^ string. This type is incompatible with
  1: var x: { y: boolean } = { y: true };
                 ^^^^^^^ boolean
```
This seems quite counter-intuitive, since flow-runtime is acting as a runtime for flow it should I suppose work the same way, I assume it's not a bug because tcomb has the same behavior, so I wonder why does it work this way?

**Comment by phpnode** [comment]
It's hard to handle this properly - one way would be to make everything a getter or setter, but this would not persist through things like `Object.assign()` or work for any objects that are created outside of flow-runtime's "scope". Another option would be to rely on some kind of static analysis in the babel plugin, to track the subjects of these assignments. We tried this approach in `babel-plugin-typecheck`, and it's hard to get right and the failure mode is very bad - valid code stops working, so we're leaving the static analysis to Flow itself. While we won't catch the error at assignment time, we will catch it if you e.g. return the object from a function with an appropriate return type.
