### ISSUE TITLE
Could not reference the given type, try t.typeOf(value) instead

### ISSUE THREAD

**Issue by FredyC** [codemix/flow-runtime#98]
This is a:

 - [x] Bug Report

Which concerns:

 - [x] flow-runtime

---

### What is the current behavior?
I have a module using flow-runtime which I have linked (`yarn link`) into my app which also is using flow-runtime. It means that imported module has it's own `node_modules/flow-runtime` due to nature of how _link_ works.

When I import some type from this module and try to use it, I am getting the warning `Could not reference the given type, try t.typeOf(value) instead.`.

I've investigated the problem and it seems that [this line](https://github.com/codemix/flow-runtime/blob/eecbcc7f9a21f9307abcc5dc1a1bf92ba4faa57e/packages/flow-runtime/src/TypeContext.js#L944) is the source of the problem as `instanceOf` does not really work in these scenarios across two modules.

There is no issue when imported module is installed normal way or by simply removing nested `flow-runtime` so it uses the same one.

---

### What is the expected behavior?
Would be nice not to see the warning in this case or at least make it somehow more descriptive so it's more obvious why it's happening. Perhaps employ some form of duck typing instead of relying on class, eg. check for `reveal` function.

---

### Which package versions are you using?
NodeJS 6.10.1
"flow-runtime": "^0.10.0",
"babel-plugin-flow-runtime": "^0.10.0",
"babel-plugin-syntax-flow": "^6.18.0",
"babel-plugin-transform-decorators-legacy": "^1.3.4",

**Comment by phpnode** [comment]
hmm, this requires some thought - fixing this particular line will just move the problem elsewhere. We use `instanceof` a lot in the codebase, but doing so helps Flow itself, so removing it is tricky. Maybe the solution is to have an ugly `global.___FLOW_RUNTIME_UNSAFE__` which would always return the existing instance if one exists.

**Comment by FredyC** [comment]
It's not necessarily about removing `instanceOf`, but adding extra check using duck typing when everything else fails. It would be probably best to unite this into one place that can do this sort of validation.

**Comment by phpnode** [comment]
we use it everywhere, so it'd be a big job to add duck typing too, i think setting a global var, as ugly as it is, is probably the most reasonable way to approach this. We can emit a warning if the versions mismatch.

**Comment by FredyC** [comment]
I don't understand if that global variable is meant as a workaround I have to use, or it's something you consider to implement. I could certainly use some more permanent solution, and it's kinda spamming me during unit testing :)

**Comment by phpnode** [comment]
flow runtime itself would look for a variable called something like `__FLOW_RUNTIME_GLOBAL_CONTEXT_UNSAFE__` - if it exists then calls to `import t from 'flow-runtime` would return that variable rather than a new copy of flow runtime's type context, if it doesn't exist we'd set it on the global.

**Comment by FredyC** [comment]
I see. I think that's a good solution given the circumstances and that it's not happening for a regular use. 👍

**Comment by phpnode** [comment]
@FredyC released in v0.12.0 let me know if this is still a problem.

**Comment by FredyC** [comment]
Awesome, will check it out soon, thanks !
