### ISSUE TITLE
Allow customizing warning message

### ISSUE THREAD

**Issue by vjpr** [codemix/flow-runtime#99]
This is a:

 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [ ] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

Warnings are logged using `console.warn`

---

### What is the expected behaviour?

1. I want to customise the warning message (use a custom logging library like `debug`, change color to yellow, add some warning emoticons to draw attention, provide clickable iTerm hyperlinks to the file etc.)
2. I want to show a growl notification when running in node env.

---

**Comment by vjpr** [comment]
Okay looks like its as simple as:

```
import t from 'flow-runtime'

t.emitWarningMessage = (message) => console.log('LOG', message)
```

**Comment by vjpr** [comment]
Reopening because I can't figure out how to get the filename where the error occurred.

**Comment by vjpr** [comment]
I managed to get the file in Node.js by walking up the stack using code like this:

```
import stackTrace from 'stack-trace'
import fse from 'fs-extra'
const DEFAULT_INDEX = 0
function getCallerFile(index = 0) {
  let err = new Error()
  const stack = stackTrace.parse(err)
  const line = stack[DEFAULT_INDEX + index]
  const fileName = line.getFileName()
  const realpath = fse.existsSync(fileName) ? fse.realpathSync(fileName) : ''
  return {
    path: line.getFileName(),
    realpath,
    line: line.getLineNumber(),
    col: line.getColumnNumber(),
    functionName: line.getFunctionName(),
    native: line.native,
  }
}
```

**Comment by phpnode** [comment]
Yeah i think the existing `emitWarningMessage()` code should be enough to do what you want to do, even if the filename hack is a bit ugly there's no other nice way for us to do it within flow-runtime itself.

**Comment by vjpr** [comment]
Thanks, I agree.
